### ISSUE TITLE
Vial of Mercy does nothing

### ISSUE THREAD

**Issue by EmSalce** [Clark919/ExpandedClasses#2]
Not sure if it's a conflict between mods or something, but right-clicking with Vial of Mercy does nothing, even if you have full serum

**Comment by Clark919** [comment]
Make sure you have the following before using the Vial:
- You have selected Apothecary as your class.
- The Vial of Mercy is in your offhand.
- You have Serum (resource meter).

Right-clicking with all of these criteria met should fire a "beam" from the centre of your screen (it can be a bit difficult to see) and play a sound effect, you can see a [GIF of the ability functioning here](https://origination.gitbook.io/origination-1.19.2/origins-information/list-of-playable-classes/apothecary). The first entity it hits should receive a heal.

The Vial functions through a power the Apothecary has, so you have to be an Apothecary for it to work. The Vial does not do anything by itself as an item. If this solves your problem, I will close the issue. Cheers :)
